version: '3'
services:
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - 3000:3000
  #   image: mentalhealth:client
  backend:
    build:
      context: ./backend
    ports:
      - 5100:5100
    image: mentalhealth
networks:
  default:
    external: true
    name: backend